import React from "react";
import BlogLayoutOne from "../components/BlogLayoutOne";
import Categories from "../containers/Categories";
import { getHighlightsPosts } from "../services";
import styles from "../styles/Blog.module.css";
import { useSelector } from "react-redux";
import { selectMode } from "../features/darkModeReducer";
import PostsWidget from "../components/PostsWidget";
import Head from "next/head";

const Blog = ({ posts }) => {

  const mode = useSelector(selectMode);

  return (
    <div className={styles.blogPostPage}>
      <Head>
        <title>TechForNerd - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.blogPostsSection}>
        <BlogLayoutOne posts={posts} />
      </div>
      <div className={styles.blogWidgetSection}>
        <div className={styles.trendingTopics}>
          <h3 style={{color: mode ? 'white' : 'black'}}>Trending Topics</h3>
          <Categories />
          <PostsWidget />
        </div>
      </div>
    </div>
  );
};

export default Blog;

export async function getStaticProps() {
  const posts = (await getHighlightsPosts()) || [];
  return {
    props: { posts },
  };
}
