import Head from "next/head";
import styles from "../styles/Home.module.css";
import { FeaturedPostBox } from "../containers";
import {
  getFeaturedPosts,
  getHighlightsPosts,
  getCategories,
  getRecentPosts,
  getTrendPosts,
} from "../services";
import { BsHourglassTop } from "react-icons/bs";
import HighlightsPosts from "../components/HighlightsPosts";
import { useSelector } from "react-redux";
import { selectMode } from "../features/darkModeReducer";
import SocialMedia from "../components/SocialMedia";
import { useEffect, useState } from "react";
import Categories from "../containers/Categories";
import RecentPosts from "../components/RecentPosts";
import { MdOutlineDownloadForOffline } from "react-icons/md";
import TextCarousel from "../components/TextCarousel";


export default function Home({ featuredposts, trendposts }) {
  const mode = useSelector(selectMode);

  const [highlightposts, setHighlightPosts] = useState([]);
  const [categories, setCategories] = useState([]);
  const [recentPosts, setRecentPosts] = useState([]);

  useEffect(() => {
    getHighlightsPosts().then((posts) => setHighlightPosts(posts));
    getCategories().then((categories) => setCategories(categories));
    getRecentPosts().then((rcposts) => setRecentPosts(rcposts));
  }, []);

  return (
    <div className={styles.home} id="home">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <TextCarousel trendPosts={trendposts} />
      <FeaturedPostBox featuredPosts={featuredposts} />
      <section
        className={styles.topHighlightsPosts}
        id="topHighlightsPosts"
        style={{ color: mode ? "white" : "black" }}
      >
        <div className={styles.highlightLeftDiv}>
          <div style={{ color: mode ? "white" : "black" }}>
            <div className={styles.highlightTitleDiv}>
              <BsHourglassTop fontSize="3.5em" />
              <h1>Today's top highlights</h1>
            </div>
            <p>Latest game coupon codes, tutorials, hacks and nerdy news</p>
          </div>
          <div className={styles.highlightLeftSection}>
            <div className={styles.highlightsPostsBox}>
              {highlightposts.map((post) => (
                <HighlightsPosts post={post} key={post.id} />
              ))}
            </div>
            <div
              className={styles.morePostButtonDiv}
              onClick={() => console.log("click")}
            >
              <button
                className={styles.morePostsButton}
                onClick={() => loadmMoreItems(endCuro)}
              >
                Load more posts{" "}
              </button>
              <MdOutlineDownloadForOffline />
            </div>
          </div>
        </div>
        <div className={styles.highlightRightDiv} id="highlightRightDiv">
          <SocialMedia />
          <div className={styles.categoriesBox}>
            <h1>Trending Topics</h1>
            {categories.map((category) => (
              <Categories
                key={category.name}
                title={category.name}
                slug={category.slug}
                photoUrl={category.photo.url}
              />
            ))}
          </div>
          <div className={styles.recentPostnAd} id="recentPostnAd">
            <div className={styles.recentPostsBox}>
              <h1>Recent Post</h1>
              {recentPosts.map((post) => (
                <RecentPosts
                  key={post.id}
                  title={post.title}
                  slug={post.slug}
                  photoUrl={post.featuredImage.url}
                  createdAt={post.createdAt}
                />
              ))}
            </div>
            <div
              className={styles.addShowDiv}
              id="container"
              // onMouseEnter={ani_add}
              // onMouseLeave={ani_add}
            >
              <h1>Ads Will be Shown Here...</h1>
            </div>
          </div>

          {/* Recent Posts */}
        </div>
      </section>
    </div>
  );
}

export async function getStaticProps() {
  const featuredposts = (await getFeaturedPosts()) || [];
  const trendposts = (await getTrendPosts()) || [];
  return {
    props: { featuredposts, trendposts },
  };
}
// export async function getServerSideProps() {
//   const featuredposts = (await getFeaturedPosts()) || [];
//   const trendposts = (await getTrendPosts()) || [];
//   return {
//     props: { featuredposts, trendposts },
//   };
// }
